FROM ubuntu:latest
WORKDIR /home/
RUN apt-get --yes update
RUN apt-get --yes install python3 python3-pip git
RUN git clone https://gitlab-smr3646.ictp.it/ali-mahani/group1-planetary-motion.git
#RUN python3 -m pip install -r group1-planetary-motion/requirements.txt
