apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web
  template:
    metadata:
      labels:
        app: k8s-web
    spec:
      containers:
        - name: k8s-web
          image: saliei/k8s-web
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
