apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-web-nginx
  template:
    metadata:
      labels:
        app: k8s-web-nginx
    spec:
      containers:
        - name: k8s-web-nginx
          image: saliei/k8s-web-nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-web-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-nginx
  ports:
  - port: 3333
    targetPort: 3000
