#!/usr/bin/env python

import sys
from typing import NoReturn
from utils import load_data, get_args, \
        land_or_water, plot_data, \
        load_earthquakes

mapfile = "gl-latlong-1km-landcover.bsq"
earthquakefile = "events_4.5.txt"

def land_cover() -> NoReturn:
    """Main function to check if the coordinate falls in land or on water.

    This function will first load (see `load_data` documentation) the data, 
    and then will get the latitude and longitude coordinates either from 
    positional arguments or from STDIN (in which, user has to trigger EOFException 
    to exit from the program) and will print 'Land' if it's on land, or will print 
    'Water' if it's on water.

    Raises:
        ValueError: If the number of arguments from STDIN does not equal to two.

    """
    data = load_data(mapfile, lazyload=True, printinfo=False)

    lat, lon = get_args()
    if (lat is None) or (lon is None):
        for line in sys.stdin:
            args = line.split()
            if len(args) != 2:
                raise ValueError("Exception occured during parsing arguments.\n\
                        See usage: ./landcover --help")
                exit(1)
            else:
                lat = np.float(args[0])
                lon = np.float(args[1])
                land_or_water(data, lat, lon)
    else:
        land_or_water(data, lat, lon)

    # Uncomment following line to also plot the data
    # image = plot_data(data, colormap="default", detailed=False)


def earthquake_land_or_wate() -> None:
    """Main function to check if earthquake happend on land or on water.

    This function will first load the world map data, and then the earthquake 
    file, and then will print for each earthquake the time of the event, and 
    if it happened on land or on water.

    """
    map_data = load_data(mapfile)
    date_lat_lon = load_earthquakes(earthquakefile)
    for earthquake in date_lat_lon:
        print("{:26} ".format(str(earthquake[0])), end='')
        land_or_water(map_data, earthquake[1], earthquake[2])


if __name__ == "__main__":
    # earthquake_land_or_wate()
    land_cover()

